log_level: info

server:
  address: 127.0.0.1
  port: 9001
  graceful_timeout: 5

additional:
  presets_file: /Users/kodix/presets.json
  local_storage_dir: ./storage
  local_client_dir: /Users/kodix/Downloads