log_level: info

clear_storage: true
image_client: http
log_image_client: true

server:
  address: 127.0.0.1defa
  port: 9001
  graceful_timeout: 5

service:
  presets_file: ./examples/presets.json
  storage:
    local:
      dir: .tmp/storage
  client:
    http:
      host: http://lorempixel.com
    local:
      dir: ./examples/images